"""
Train Expert Models using generated training data.

This script trains all three expert models using the data generated by
scripts/generate_training_data.py
"""

import json
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.metrics import accuracy_score, f1_score, classification_report

# Add parent directory to path
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from clinical.experts.microbiome_expert import MicrobiomeExpert
from clinical.experts.metabolome_expert import MetabolomeExpert
from clinical.experts.proteome_expert import ProteomeExpert
from clinical.experts.model_manager import ModelManager
from clinical.preprocessing.microbiome_preprocessor import MicrobiomePreprocessor
from clinical.preprocessing.metabolome_preprocessor import MetabolomePreprocessor
from clinical.preprocessing.proteome_preprocessor import ProteomePreprocessor


def load_training_data(data_dir="data/training"):
    """Load training data generated by generate_training_data.py"""
    data_dir = Path(data_dir)

    print("Loading training data...")

    # Load omics data
    microbiome = pd.read_csv(data_dir / "microbiome_raw.csv", index_col=0)
    metabolome = pd.read_csv(data_dir / "metabolome_raw.csv", index_col=0)
    proteome = pd.read_csv(data_dir / "proteome_raw.csv", index_col=0)
    labels = pd.read_csv(data_dir / "labels.csv")

    # Load splits
    with open(data_dir / "splits.json", "r") as f:
        splits = json.load(f)

    print(f"  Microbiome: {microbiome.shape}")
    print(f"  Metabolome: {metabolome.shape}")
    print(f"  Proteome: {proteome.shape}")
    print(f"  Total samples: {len(labels)}")
    print(f"  Train samples: {len(splits['train'])}")
    print(f"  Test samples: {len(splits['test'])}")

    return microbiome, metabolome, proteome, labels, splits


def split_data(data, labels, splits):
    """Split data into train and test sets."""
    train_ids = splits['train']
    test_ids = splits['test']

    X_train = data.loc[train_ids]
    X_test = data.loc[test_ids]

    # Get labels
    label_dict = dict(zip(labels['sample_id'], labels['diagnosis']))
    y_train = pd.Series([label_dict[sid] for sid in train_ids], index=train_ids)
    y_test = pd.Series([label_dict[sid] for sid in test_ids], index=test_ids)

    return X_train, X_test, y_train, y_test


def train_expert(expert_name, expert_class, preprocessor, X_train, X_test, y_train, y_test):
    """Train a single expert model."""
    print(f"\n{'='*60}")
    print(f"Training {expert_name}...")
    print(f"{'='*60}")

    # Preprocess data
    print(f"Preprocessing data...")
    preprocessor.fit(X_train)
    X_train_processed = preprocessor.transform(X_train).data
    X_test_processed = preprocessor.transform(X_test).data

    print(f"  Training data: {X_train_processed.shape}")
    print(f"  Test data: {X_test_processed.shape}")

    # Train expert
    print(f"\nTraining {expert_name}...")
    expert = expert_class()
    expert.fit(X_train_processed, y_train, use_grid_search=False)

    # Evaluate on training set
    print(f"\nEvaluating on training set...")
    train_perf = expert.get_model_performance(X_train_processed, y_train)
    print(f"  Training Accuracy: {train_perf['accuracy']:.3f}")
    print(f"  Training F1-Score (weighted): {train_perf['f1_score']:.3f}")

    # Evaluate on test set
    print(f"\nEvaluating on test set...")
    test_perf = expert.get_model_performance(X_test_processed, y_test)
    print(f"  Test Accuracy: {test_perf['accuracy']:.3f}")
    print(f"  Test F1-Score (weighted): {test_perf['f1_score']:.3f}")

    # Detailed classification report
    y_pred = [op.diagnosis for op in expert.predict(X_test_processed)]
    print(f"\nClassification Report (Test Set):")
    print(classification_report(y_test, y_pred))

    return expert, train_perf, test_perf


def main():
    print("\n" + "="*70)
    print("Training Expert Models with Generated Data")
    print("="*70)

    # Load data
    microbiome, metabolome, proteome, labels, splits = load_training_data()

    # Print class distribution
    print(f"\nClass distribution:")
    print(labels['diagnosis'].value_counts())

    # Initialize model manager
    model_manager = ModelManager(models_dir="data/models")

    # Train microbiome expert
    print(f"\n{'#'*70}")
    print(f"# MICROBIOME EXPERT")
    print(f"{'#'*70}")

    X_train_micro, X_test_micro, y_train, y_test = split_data(microbiome, labels, splits)
    micro_expert, micro_train_perf, micro_test_perf = train_expert(
        "Microbiome Expert",
        MicrobiomeExpert,
        MicrobiomePreprocessor(),
        X_train_micro, X_test_micro, y_train, y_test
    )

    # Save model
    print(f"\nSaving Microbiome Expert...")
    model_manager.save_expert(
        micro_expert,
        notes=f"Trained on {len(X_train_micro)} samples with obvious disease features"
    )

    # Train metabolome expert
    print(f"\n{'#'*70}")
    print(f"# METABOLOME EXPERT")
    print(f"{'#'*70}")

    X_train_metab, X_test_metab, y_train, y_test = split_data(metabolome, labels, splits)
    metab_expert, metab_train_perf, metab_test_perf = train_expert(
        "Metabolome Expert",
        MetabolomeExpert,
        MetabolomePreprocessor(),
        X_train_metab, X_test_metab, y_train, y_test
    )

    # Save model
    print(f"\nSaving Metabolome Expert...")
    model_manager.save_expert(
        metab_expert,
        notes=f"Trained on {len(X_train_metab)} samples with obvious disease features"
    )

    # Train proteome expert
    print(f"\n{'#'*70}")
    print(f"# PROTEOME EXPERT")
    print(f"{'#'*70}")

    X_train_prot, X_test_prot, y_train, y_test = split_data(proteome, labels, splits)
    prot_expert, prot_train_perf, prot_test_perf = train_expert(
        "Proteome Expert",
        ProteomeExpert,
        ProteomePreprocessor(),
        X_train_prot, X_test_prot, y_train, y_test
    )

    # Save model
    print(f"\nSaving Proteome Expert...")
    model_manager.save_expert(
        prot_expert,
        notes=f"Trained on {len(X_train_prot)} samples with obvious disease features"
    )

    # Summary
    print(f"\n{'='*70}")
    print("TRAINING SUMMARY")
    print(f"{'='*70}")

    results = {
        "Microbiome Expert": (micro_train_perf, micro_test_perf),
        "Metabolome Expert": (metab_train_perf, metab_test_perf),
        "Proteome Expert": (prot_train_perf, prot_test_perf)
    }

    for expert_name, (train_perf, test_perf) in results.items():
        print(f"\n{expert_name}:")
        print(f"  Train Accuracy: {train_perf['accuracy']:.3f}")
        print(f"  Test Accuracy: {test_perf['accuracy']:.3f}")
        print(f"  Train F1-Score: {train_perf['f1_score']:.3f}")
        print(f"  Test F1-Score: {test_perf['f1_score']:.3f}")

    print(f"\n✓ Training completed! Models saved to data/models/")
    print(f"\n{model_manager.summary()}")

    print(f"\n{'='*70}")
    print("NEXT STEP: Test with mismatched data to trigger debate")
    print(f"{'='*70}")


if __name__ == "__main__":
    main()
